### ISSUE TITLE
Sleep, Wake, and Battery

### ISSUE THREAD

**Issue by shiecldk** [badstorm/surface-pro-7-opencore#39]
Hi,

I'm interested in purchasing this laptop. Sorry that I have quite a few questions...

I wonder if the sleep, wake, and battery management is working on the laptop?
Does the touchscreen work with gestures?
Does the iGPU works in Big Sur and up without flickering issue in HiDPI?
Does the brightness adjustment work?
Does the function keys work?
What's the proximate hours for the battery to stand before it runs out?
Have you tried ECEnabler.kext and/or SMCBatteryManager.kext to fix the battery?
Also, you can try to rename EC0 to EC in the ACPI patch in OpenCore for battery patch.
https://www.reddit.com/r/hackintosh/comments/n2nvf8/ecenabler_no_more_acpi_patches_for_battery_sorta/
https://github.com/1Revenger1/ECEnabler

There are also some other patches here that might help you:
https://github.com/jsassu20/OpenCore-HotPatching-Guide

As for the cameras, are they connected through USB or I2C?
Have you tried the fake id method with AnyiSightCam.kext?

**Comment by badstorm** [comment]
No I have not tried these solutions. unfortunately in this month I am not able to do further tests, but if it works and you want to send a PR it would be very welcome. :)

**Comment by shiecldk** [comment]
Got it thanks. Does the touchscreen work with VoodooI2C in your device?

**Comment by mrahmadt** [comment]
> 
> 
> This because of surface's fxxking SSH. Microsoft doesn't want us to install custom systems except Windows.
> :(

Compared to how Apple openess :)

**Comment by sauregurke** [comment]
4k60 is now fully fixed with WhateverGreen 1.5.5. (Could also be fixed with 1.5.4 but I CBA to test that; seems like the relevant fix was added in that release.)
https://github.com/acidanthera/whatevergreen/releases
You just need to add the boot arg or, for a more refined solution, add **enable-dbuf-early-optimize** to your iGPU section under deviceproperties. Tested thoroughly with macOS 11.6.1 and 12.0.1 but there's no real reason I can see for it to not work elsewhere. 
Before the flickering was intermittent; it seemed like a race condition, but I have nothing to back that up other than a light correlation between the surface being warm on startup and the flickering being present.
At some point, I will run some tests to see if the rest of the iGPU section patching is necessary with this fix, but I am pretty tired of working on the project as of late. For now, just use those fixes (they're provided here and/or under Xiashang's BigSurface repo) and add this one too. (or you can take one for the team and test yourself :))

**Comment by badstorm** [comment]
Thanks @sauregurke, add it to last commit

**Comment by badstorm** [comment]
https://github.com/badstorm/surface-pro-7-opencore/releases/tag/1776
