### ISSUE TITLE
OC not start on last Surface UEFI Firmwire 

### ISSUE THREAD

**Issue by butter1232** [badstorm/surface-pro-7-opencore#9]
Tried a bunch of time over and over and copy efi file not to sure what I’m doing wrong

**Comment by badstorm** [comment]
Hi, did you disable `Secure Boot`? 

Did you also tried [OC debug version](https://github.com/acidanthera/OpenCorePkg/releases/download/0.6.5/OpenCore-0.6.5-DEBUG.zip)?

It seams something block the OC image or the OC `.efi` file is corrupted.

**Comment by butter1232** [comment]
I give that a try and I will update you

**Comment by butter1232** [comment]
Secure Boot Has been disabled the whole time

**Comment by butter1232** [comment]
Hey it been saying the same thing 
![D14CC387-F936-4495-8BAC-6B131403331D](https://user-images.githubusercontent.com/77524018/104875111-7fa1c380-5922-11eb-8844-ee97f86a9bd2.jpeg)

Also I put the debug

**Comment by butter1232** [comment]
![669004FE-2E8E-4A3A-891A-C5382B7E19EC](https://user-images.githubusercontent.com/77524018/104876486-c7761a00-5925-11eb-9b80-fd2b2109e0be.jpeg)

**Comment by Xiashangning** [comment]
I also have this issue, it seems that if you have applied the recent Microsoft Surface Firmware Update(on Jan 7th), then the system will block you completely from booting Opencore. I tried different ways but none of them works.

**Comment by badstorm** [comment]
Thanks @Xiashangning for this information. With this update only OC is corrupted or also other OS? Have you tried to run Linux? It works?

**Comment by butter1232** [comment]
Linux work

**Comment by Xiashangning** [comment]
Yes, like you did, I have tried Ubuntu, Manjaro etc, all of them work except OC. And I have been using SP7 with Big Sur for quite a while until I updated the firmware 4 days ago... After it installed, I cannot get into OC anymore. Sad.
傻 逼 微软！

**Comment by badstorm** [comment]
Since I think is a OC related problem, I opened a issue [here](https://github.com/acidanthera/bugtracker/issues/1446)

**Comment by badstorm** [comment]
@Xiashangning @butter1232 For prevent closing the issue opened replay also you to that issue.

**Comment by Xiashangning** [comment]
@badstorm so have you tried vit9696's solution? If not, then I will try it now. Hoping that is enough T_T

**Comment by badstorm** [comment]
My Surface is not udpated with that firmware version, so for now i cannot test. Try and let me know so i can update the configuration in this repo.

**Comment by butter1232** [comment]
I will let you know

**Comment by vit9696** [comment]
In addition to the master version please also try https://github.com/acidanthera/bugtracker/issues/1354#issuecomment-766152532.

**Comment by Xiashangning** [comment]
@vit9696 , I've tried Softkbd-r6.zip and it does not work. By the way, with secure boot disabled, so far only Opencore could not been loaded by the system, Clover however can enter the booting selection screen (though I don't have a bootable config for SP7 using clover), other OS like ubuntu and manjaro work just as before. I doubt that this might be an Opencore specific issue... Perhaps there is something slightly different between Opencore and Clover?

**Comment by vit9696** [comment]
@Xiashangning i.e. you upgraded to OpenCore 0.6.6 master, and then replaced BOOTx64.efi, Bootstrap.efi, and OpenCore.efi and it failed? What exactly did happen? I would like to see the screenshots and logs from both master version and Softkbd-r6 (if they are created).

> Perhaps there is something slightly different between Opencore and Clover?

Unlike Clover and other bootloaders OpenCore is a driver and uses two-stage boot model. Both things are valid UEFI spec-wise.

**Comment by Xiashangning** [comment]
OK, I will gather the files you need, right now it dinner time so... maybe 2 hours later I will update you what I get.

**Comment by Xiashangning** [comment]
Sorry for my first comment, I was performing these trials with the boot chain: grub->OC with secure boot enabled.After I turned off secure boot and boot directly with Opencore, I have done what you asked and indeed the results are different! Here are the screenshots you must take a look at! It seems that this time, with the softkbd-r6, Opencore can read its 'core' file---Opencore.efi, but stops at loading HfsPlus.efi, reporting the same error: Access denied.
Meanwhile, I have read through the issue you mentioned above. It reminds me something. When Opencore and macOS boots, in verbose mode, the little keyboard icon shows periodically at the right-down corner, it shows when a line is completely printed, and disappears when printing another line. This 'feature' might indicate that Surface Pro thinks Opencore is a diag utility as HP does. And this firmware update has applied some so-called security limitations, so Opencore failed to load macOS since then.
The first photo is what I've got with master version
![IMG_20210125_201214](https://user-images.githubusercontent.com/18528518/105707828-7b8f2a80-5f4e-11eb-94fa-0d3f6232ff00.jpg)
These two is with Softkbd-r6. The last one is just wanting to show you that the icon can be clicked and functions as a screen keyboard.
![IMG_20210125_202920](https://user-images.githubusercontent.com/18528518/105707916-a2e5f780-5f4e-11eb-9ff0-35851c314c6c.jpg)
![IMG_20210125_203027](https://user-images.githubusercontent.com/18528518/105707928-a7aaab80-5f4e-11eb-8b88-25496a8f6640.jpg)
And the latter method does make Opencore boot, so here is the log file.(There isn't one for the master version since it won't boot)
[opencore-2020-10-20-161155.txt](https://github.com/badstorm/surface-pro-7-opencore/files/5866603/opencore-2020-10-20-161155.txt)

**Comment by vit9696** [comment]
So, this confirms that Microsoft broke UEFI driver loading through the bootloader in their firmware (thus the `Access Denied` message), which is a bug on their side. I suggest you file a support inquiry on them.

I am not positive there is an immediate workaround for that, and to be honest I am not sure there even is a complicate way to workaround it. Therefore I strongly advise to refrain from upgrading to this firmware and downgrade if possible.

From you I would like to see:
- all the BIOS preferences available on the laptop
- firmware dump
- trying to boot any OS without any drivers (it will likely fail with macOS, but Windows might work)
- trying to make a working clover setup and/or checking if it can load HFSDriver or it just silently fails

**Comment by Xiashangning** [comment]
1. All of the BIOS setting are as follow, they are just incredibly few! (STUPID Microsoft)
[BIOS settings.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5866792/BIOS.settings.zip)

2. Do you mean the BIOS dump? because the firmware update came within the Windows update, and I cannot find the cache files on my disk any more, maybe it got deleted automatically by Windows? (Since the update took place 8 days ago) So what I have now is the BIOS dump via an exe called 'BIOS backup', I don't know the exact size of Surface's BIOS so it is 16M. Maybe someone who haven't updated his firmware yet can download it so we can get the exact update files.
Or there might exist some software for firmware dumping?
[surface.bin.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5866895/surface.bin.zip)

3. What do you mean trying to boot any OS without any drivers? Is that testing the booting process of Windows, Ubuntu, Manjaro etc. ? Well, they are all just fine (like before) I can enter the desktops of these OS without any issue. Also, Clover seems to behave nothing different.

4. OK, I will try.

**Comment by vit9696** [comment]
3. I meant removing UEFI Driver entries from config.plist and trying to boot an operating system from OpenCore. E.g. macOS, Windows, Ubuntu.

**Comment by Xiashangning** [comment]
Nope, I tried Windows PE, it report a software error with black screen and the cursor is invisible(I can move it around and click the task manager I invoked by pressing the keyboard) and Ubuntu boot into a black screen after I choose 'try ubuntu without installing'. macOS stops at the same place, as before and as those HP laptops do. ([EB|#LOG:EXITBS:START])

**Comment by Xiashangning** [comment]
Sorry I forgot the logs
[Ubuntu.txt](https://github.com/badstorm/surface-pro-7-opencore/files/5867596/Ubuntu.txt)
[windows PE.txt](https://github.com/badstorm/surface-pro-7-opencore/files/5867597/windows.PE.txt)
[macOS.txt](https://github.com/badstorm/surface-pro-7-opencore/files/5867593/macOS.txt)

**Comment by vit9696** [comment]
Please return the drivers back and try this OpenCore.efi version instead of the one found in SoftKbd-r6. I will need the logs.

[SoftKbd-r6+.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5870378/SoftKbd-r6%2B.zip)

**Comment by vit9696** [comment]
Sorry, uploaded the wrong file in the previous post. This one is correct.

[SoftKbd-r6++.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5870392/SoftKbd-r6%2B%2B.zip)

**Comment by Xiashangning** [comment]
This time, the drivers are loaded but Opencore halted at ASSERT [OpenCore] Header.c(59): Context->FileSize != 0 after injecting the kexts.
[opencore-2021-01-26-101634.txt](https://github.com/badstorm/surface-pro-7-opencore/files/5870770/opencore-2021-01-26-101634.txt)

**Comment by vit9696** [comment]
To understand why this assertion happened I will need two things: your EFI folder and BootKernelExtensions.kc from /System/Library/KernelCollections. For the time being I simply added a workaround for the build.

[SoftKbd-r6f.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5872485/SoftKbd-r6f.zip)

**Comment by Xiashangning** [comment]
@vit9696  Sorry for the delay, here are my EFI folder and the BootKernelExtensions.kc, since the AirportItlwm.kext and IntelBluetoothFirmware.kext are too large. I remove these two kexts
[EFI and .kc.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5873082/EFI.and.kc.zip)

**Comment by vit9696** [comment]
@Xiashangning

Does r6f boot macOS? If it does, can I see the log?

With the EFI folder attached I was unable to quickly reproduce the issue and will need your help. To be able to reproduce the assertion issue (you had with r6++), you will need to (temporarily, as you do not need this quirk) set `SetApfsTrimTimeout` to 0 in the `config.plist`. Please do that and confirm that you run into the assertion. Afterwards find a minimal set of kexts that still causes the assertion (by disabling them) and attach the EFI folder with all these kexts here.

**Comment by Xiashangning** [comment]
Sadly, no, still stops at [EB|#LOG:EXITBS:START], the log file is attached.
[opencore-2021-01-26-195525.txt](https://github.com/badstorm/surface-pro-7-opencore/files/5873148/opencore-2021-01-26-195525.txt)

I will do it right now.

**Comment by vit9696** [comment]
If it stops, this should now be a quirk issue, likely Booter or Kenrel, as we addressed the security issues Microsoft added, but cannot address the configuration changes required (if any).

**Comment by Xiashangning** [comment]
Sorry sir, but I think this is a universal problem... I tried all my kexts one by one, all reporting the same error. So the minimal set of kexts is all of my enabled kexts in my previous EFI folder

**Comment by vit9696** [comment]
Does it reproduce with just the Lilu enabled? The problem is that I cannot reproduce it here with the minimal environment so far.

**Comment by Xiashangning** [comment]
And as for the Booter and Kernel quirks, do you have some ideas on what should I test? ( a suspicious range of quirks that perhaps works) Given that there are some many of them and testing all of the combinations is impossible.

**Comment by Xiashangning** [comment]
@vit9696 Yes, this is the first kext I test with SetApfsTrimTimeout=0

**Comment by vit9696** [comment]
@Xiashangning very interesting. I wonder if the .kc on the system volume and the preboot volume are different then. Could you upload the whole APFS Preboot volume somehow?

As for quirks… it is a difficult question, I will try to list my first thoughts below:

- `AppleXcpmCfgLock` ← check whether M$ locked the CFG register, VerifyMsrE2 tool is your friend. If they did, enable it.
- `LapicKernelPanic` ← there is a low probability for this to be needed, but you could try enabling.
- `IgnoreInvalidFlexRatio` ← same here.
- `ReleaseUsbOwnership` ← sometimes enabling it can cause issues, so try both on and off.
- You have MAT supported, enabling `EnableWriteUnprotector` may be unreasonable. I would try `EnableWriteUnprotector` = NO, `RebuildAppleMemoryMap` = YES, `SyncRuntimePermissions` = YES.
- Also possibly `SetupVirtualMap` = YES, `ForceExitBootServices` = YES and `ProtectMemoryRegions` = YES.

It would be best to back these quirks on the older firmware as well. To see if they affect it.

**Comment by Xiashangning** [comment]
Okay, but how could I mount the Preboot volume? I failed...

**Comment by vit9696** [comment]
Well, do you have access to macOS on another computer? If yes, you can mount it with diskutil. See diskutil list, and then diskutil mount for the relevant colume.

**Comment by Xiashangning** [comment]
Whoops, I mounted my system Preboot volumes by mistake...
Here is it. My Preboot volume of Surface Pro 7.
https://drive.google.com/file/d/1Am63_URTYorO5lLL6nWwN6sNq4Y5eQRI/view?usp=sharing

**Comment by vit9696** [comment]
Requested access. Did you try the quirks?

**Comment by Xiashangning** [comment]
Will try the Quirks tomorrow, thanks. Sorry for the permission, I haven't used Google Drive before, so it took me sometime to figure out the configurations.

**Comment by vit9696** [comment]
Ok, this one should fix the assertion. Will look forward for the quirk results.

[SoftKbd-r7.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5875102/SoftKbd-r7.zip)

**Comment by vit9696** [comment]
OpenCore 0.6.6 from master (1651cef and newer) contains all the relevant changes included in r7. To enable UEFI driver loading on Microsoft Surface one needs to activate `DisableSecurityPolicy`. After checking the assertion in r7, please confirm that master version works as desired, and execute quirk tests on it.

**Comment by Xiashangning** [comment]
OpenCore 0.6.6 from master works as well as r7 does. Sadly, none of the Quirks works for me. Perhaps I have to report this to Microsoft hoping they would offer a tool to flash the firmware back.

**Comment by vit9696** [comment]
Well, just trying them one by one is not really a good way to check. Neither is enabling them all. Are you using `-v` and can make sure that you will see any difference in the OS output if it happens?

If so, let's start with simple things.

- Is E2 locked? I.e. I directly asked you to check whether it is through VerifyMsrE2.
- Are you checking Big Sur exclusively? I'd suggest you also check Catalina DMG recovery due to some kernel changes.

**Comment by vit9696** [comment]
Actually, considering the HP issue, I wonder if USB boot is any different from SSD boot.

**Comment by Xiashangning** [comment]
1. E2 is unlocked, I already checked it. Just forgot to mention it.
2. That is a good idea, thanks. I will try to install Catalina to see if bootable.
3. In fact, whether I turned these quirks on or off, I am pretty sure that near [EB|#LOG:EXITBS:START], there is nothing changed... As for the whole log, I will use some tool to compare the difference of the logs.
4. I am booting from external SSD drive(USB3.0) and OK I will give it a try to copy my EFI folder directly into the internal SSD.

**Comment by Xiashangning** [comment]
When booting Catalina, there is some slight difference.
before [EB|#LOG:EXITBS:START], it shows [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49
while in Big Sur, it shows #[EB.B.WFDW|!WF] Err(0xE) 0

By the way, There is a line "OC: Changed resolution to 0x0@0 (max: 1, force: 0) from Max - Already started" is that Okay? Since it says resolution is 0x0...

Here are the logs(I kept ForceExitBootServices = YES, ProtectMemoryRegions = YES, LapicKernelPanic = YES and IgnoreInvalidFlexRatio=YES because enabling or disabling shows nothing different in Big Sur)
[catalina.txt](https://github.com/badstorm/surface-pro-7-opencore/files/5880606/catalina.txt)
[big sur.txt](https://github.com/badstorm/surface-pro-7-opencore/files/5880607/big.sur.txt)

**Comment by vit9696** [comment]
Max resolution message is ok. Max: 1 means that the largest is chosen. I believe you should try locating the "freezing" function with the same reset approach as suggested in https://github.com/acidanthera/bugtracker/issues/1354. Please try doing that, and let me know the function it does reach last and the first it does not.

**Comment by 24532** [comment]
I have the same problem. I hope the author can solve it.

**Comment by vit9696** [comment]
Well, you were told what to do. Start with https://github.com/acidanthera/bugtracker/issues/1354#issuecomment-768124385 and onwards.

**Comment by 24532** [comment]
@vit9696  I have backed up the old version of UEFI firmware (version: 8.100.140.0). Now I can recover to this driver. I don't know if it can work?

**Comment by vit9696** [comment]
I have no idea how to downgrade firmware on M$ Surface.

**Comment by 24532** [comment]
@vit9696  You can leave your email address and I'll send it to you.

**Comment by 24532** [comment]
This is an old version of the firmware driver. You can try to rollback the driver to the old version.



---Original---

**Comment by Xiashangning** [comment]
@vit9696  @24532  I am a little busy these days, will test your comments' methods ASAP.

**Comment by Xiashangning** [comment]
@vit9696 I am back, sorry for the delay. I have tried your early reboot patch, but it freezes instead of reboot. So it seems that it stops even before _vstart.

**Comment by vit9696** [comment]
Hi @Xiashangning, this is very strange, unless this way of rebooting simply does not work for the platform. Same for  `_pstart`? Maybe the recent changes to booter (?) quirks actually broke it (more), and we need to revert? Can you provide an ACPI dump?

**Comment by Xiashangning** [comment]
Sure. I will try _pstart, I have reverted to the original config which is okay before the firmware update. If it does not work, maybe I should try change the quirks then.
[SP7 ACPI.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5899236/SP7.ACPI.zip)

**Comment by Xiashangning** [comment]
To try _pstart, simply change the <base> value to _pstart, is that correct?

**Comment by vit9696** [comment]
Yes, correct.

**Comment by vit9696** [comment]
According to ACPI dump the reset register is all the same:

```
[074h 0116  12]               Reset Register : [Generic Address Structure]
[074h 0116   1]                     Space ID : 01 [SystemIO]
[075h 0117   1]                    Bit Width : 08
[076h 0118   1]                   Bit Offset : 00
[077h 0119   1]         Encoded Access Width : 01 [Byte Access:8]
[078h 0120   8]                      Address : 0000000000000CF9
```

As long as it hits the command it should reset really :x

**Comment by Xiashangning** [comment]
Nope, _pstart failed to reboot also....

**Comment by vit9696** [comment]
Yes… because _vstart/_pstart are very early, unless the memory is unaccessible, it should reboot just fine. Still, would help a lot to confirm that it does reboot on the older firmware. Could be some special code not letting us reboot that early.

**Comment by vit9696** [comment]
I added better fb logging in https://github.com/acidanthera/OpenCorePkg/commit/69ff426319579afbb6085fccb5eaab602f9f7337.

In addition to MmapDump, please redo the logs with it. Will appear soon on https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

**Comment by 24532** [comment]
@vit9696  it may be fixed in 0.6.6 (you can download it at gitee.com/shuiyunxc/Opencore And the pwd is 544133143 for the zip file)


0.6.6：Added DisableSecurityPolicy UEFI quirk to workaround driver loading

Improved ocvalidate checks in Misc, NVRAM, and UEFI sections

from jackjack1-su

You can try it.

**Comment by Xiashangning** [comment]
Well, I am so desperate right now. It is not because I cannot boot OC successfully, but I haven't observed ANY changes in logs no matter what I have tried: quirks, early reboots etc. No matter what combination of quirks I use, it ALWAYS stops at [EB|#LOG:EXITBS:START], not even a line has changed! So now I am thinking if I could add more log prints into OpenCore by myself. So @vit9696 
1. "[EB|#LOG:EXITBS:START]" is this a log printed by OC? 
2. If so, where is this line exactly in the source file?
3. If not, then which part of OC code is most nearby to this log?
I want to add a ton of log prints to see where my OC stops.

**Comment by vit9696** [comment]
Ah, there may be some big confusion.

This line is printed by boot.efi, and it means that UEFI phase is over, the kernel is being started. Since this print, no prints are possible before the XNU kernel initialises (pstart, vstart, and several more functions). There is a small part of UEFI code (both from boot.efi and OpenCore) executing afterwards, but most of it is XNU.

The earliest prints possible from XNU can only go through COM port. Onscreen prints (with -v) can only happen much later, so there is a large part of the XNU code that executes without anything visible.

To understand what exactly is executing and what is not, we can try to utilise other ways of reporting. A direct reboot through the registers is one of such ways, but sadly it is not available on many boards. I.e. you insert a patch to reboot your system at a certain step, if it does reboot (instead of the usual hang), you know that the code executed and no panic happened that early.

**Comment by vit9696** [comment]
The OpenCore code I mentioned to execute after this message (in parallel with boot.efi through hooks) is here:
- https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Library/OcAfterBootCompatLib/ServiceOverrides.c#L928
- https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Library/OcAfterBootCompatLib/ServiceOverrides.c#L1010
- 
https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Library/OcAfterBootCompatLib/KernelSupport.c#L709

You cannot print there, at most you can use DirectResetCold function to trigger a reboot.

**Comment by Xiashangning** [comment]
Copy that, thank you so much!

**Comment by Xiashangning** [comment]
It stops before XNU entry point. I inserted the Reset function at the first line of AppleMapPrepareKernelState, but it did not reboot. When I inserted it at the other two functions above, the system did reboot.

**Comment by vit9696** [comment]
*Reset* or DirectResetCold? You can only call the latter this late in the code. The function comes from OcMiscLib.h. Find the place within all the three. They are ordered in call order.

**Comment by Xiashangning** [comment]
My bad, DirectResetCold.
Okay, in fact I tried to insert the DirectResetCold function somewhere else I thought suspicious, now that I know they are called one after another. I will update you the exact place

**Comment by Xiashangning** [comment]
@vit9696 I trace the code down to AppleMapPrepareMemState
Since there are two settings in this function, so I have tried all the four combinations and I confirm that it stops at gRT->SetVirtualAddressMap
https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Library/OcAfterBootCompatLib/KernelSupport.c#L685

**Comment by vit9696** [comment]
Right, what are your current booter quirks?

**Comment by Xiashangning** [comment]
The one I used now is AvoidRuntimeDefrag=YES, ProtectUEFIServices=YES, RebuildAppleMemoryMap=YES and SyncRuntimePermissons=YES and the rest NO

**Comment by Xiashangning** [comment]
AvoidRuntimeDefrag=YES, ProtectUEFIServices=YES these two are the ones concerned in AppleMapPrepareMemState and I have tried the 4 possible combinations

**Comment by Xiashangning** [comment]
AvoidRuntimeDefrag and SetupVirtualMap are the two settings concerned in AppleMapPrepareMemState and I have tried the 4 possible combinations

**Comment by vit9696** [comment]
Not just these. Actually there are several more relevant ones:

- RebuildAppleMemoryMap
- SyncRuntimePermissions
- ProtectUefiServices

The SetVirtualAddressMap is routed to OpenRuntime, [here](https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Platform/OpenRuntime/UefiRuntimeServices.c#L740). If you cannot reach this place, then OpenRuntime is not properly mapped for some reason. Why — could be due to these quirks.

**Comment by Xiashangning** [comment]
To be more precise, the code stops at if(SetupVirtualMap)...else...
I will check it tomorrow, thanks again!
Have a good day/night :D

**Comment by vit9696** [comment]
Well, check if you can reach OpenRuntime tomorrow…

**Comment by Xiashangning** [comment]
It does reach OpenRuntime and stops at mCustomSetVirtualAddressMap, once again, please tell me where is its implementation
https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Platform/OpenRuntime/UefiRuntimeServices.c#L767

**Comment by vit9696** [comment]
Here: https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Library/OcAfterBootCompatLib/ServiceOverrides.c#L1010

**Comment by Xiashangning** [comment]
What? So you mean the calling sequence is 
OcSetVirtualAddressMap => AppleMapPrepareMemState => gRT->SetVirtualAddressMap => WrapSetVirtualAddressMap => mCustomSetVirtualAddressMap => OcSetVirtualAddressMap => AppleMapPrepareMemState, then the code recalled ProtectRtMemoryFromRelocation for the second time and next called gRT->SetVirtualAddressMap but this time it is the original implementation by UEFI firmware(mSetVirtualAddressMap)?

**Comment by vit9696** [comment]
The calling sequence is:
- OcStartImage
- EfiBoot code
- OcGetMemoryMap (possibly many times)
- EfiBoot code
- OcExitBootServices
- EfiBoot code
- WrapSetVirtualAddressMap in OpenRuntime
- OcSetVirtualAddressMap in OpenCore (OcAfterBootCompatLib, it is custom handler indeed)
- AppleMapPrepareMemState
- Eventually gRT->SetVirtualAddressMap, which now points to original BIOS SetVirtualAddressMap. Through either PerformRtMemoryVirtualMapping or direct gRT->SetVirtualAddressMap.
- EfiBoot code
- AppleMapPrepareKernelState
- XNU code

**Comment by Xiashangning** [comment]
Understood, so it actually stops at the original BIOS SetVirtualAddressMap, then is there anything I can do to go further? I am now trying with the quirk SetupVirtualMap=YES and testing where the code stops inside PerformRtMemoryVirtualMapping

**Comment by Xiashangning** [comment]
But as your document says, modern firmware with memory protection doesn't support the quirk SetupVirtualMap, so I am wondering if testing SetupVirtualMap=YES won't help, for now I find that it stops inside the for loop of PerformRtMemoryVirtualMapping, still debuging...

**Comment by vit9696** [comment]
Whether or not SetupVirtualMap quirk is supported — it depends, but indeed it should neither be needed with modern firmware, nor it actually is supported. The explanation is provided in this issue: https://github.com/acidanthera/bugtracker/issues/719.

If the code does not proceed after calling the original BIOS SetVirtualAddressMap, i.e. both with this quirk enabled and disabled, then it is very worrying. Basically there could be two possibilities:

- Either it indeed dies within the BIOS services, and we will need to understand what is special with the OC compared to e.g. Windows bootloader.
- Or it simply cannot reboot after SetupVirtualMap through DirectResetCold. In this case we can try using other methods to check whether the code is reachable. For instance, we can write memory to RTC and check after a hard reboot.

**Comment by Xiashangning** [comment]
Suppose that we cannot reboot using DirectResetCold, could you please tell me how to write RTC into memory in code and then how can I obtain it(through OpenShell?)
PS: I have searched online for tutorials about UEFI BIOS and try to learn something by myself. I am a programmer but unfortunately not in this domain...

**Comment by vit9696** [comment]
You can use https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Include/Acidanthera/Library/OcRtcLib.h. Please add the library dependency to the .inf file as needed (see LibraryClasses). Write some value at a reasonably high index (e.g. 255, so it does not collide with the firmware) and use RtcRw.efi to read it from Shell.

**Comment by vit9696** [comment]
I believe we did get things to move, at least on some models. Please check https://github.com/acidanthera/bugtracker/issues/1486#issuecomment-781062621. This may be able to help with Microsoft Surface as well.

**Comment by Xiashangning** [comment]
@vit9696 !!! That is exactly what the Surface Pro series need !!!
I have built the master version of OC and enabled SetupVirtualMap.
macOS boots just smoothly as before T_T finally!
Thank you all for your wonderful work!

**Comment by badstorm** [comment]
@Xiashangning you resolve your issue? What you edited in this configuration to solve the problem? 
So i can update this repo. 
Thanks

**Comment by Xiashangning** [comment]
@badstorm Use the master version of OpenCore and enable 'DisableSecurityPolicy' quirk in UEFI section
Besides, I believe the commands for the touchpad are not correct, you should delete all the 'sudo' because with it the commands have no effect. Without 'sudo', the configuration works on my SP7
PS: I have a method to boot macOS with MS Secure Boot on ( using grub to boot OC then macOS), don't know if you want to have a try.

**Comment by Xiashangning** [comment]
In that way, we can remove the annoying red unlock icon

**Comment by badstorm** [comment]
Sure, if you want to help imporving this configuration you are very welcome. Please send a PR with this booting alternative so we can test it.

Ok, about the problem in this issue I wait for thre release of OC 0.66 to update the documentation.

Thanks

**Comment by Xiashangning** [comment]
@badstorm PR sent.
PS: How can I submit a PR for a new branch for testing my booting alternative?

**Comment by badstorm** [comment]
https://opensource.com/article/19/7/create-pull-request-github

**Comment by badstorm** [comment]
Fixed in Release 1667
