### ISSUE TITLE
wifi issue on surface pro 7 

### ISSUE THREAD

**Issue by skydiives2** [badstorm/surface-pro-7-opencore#91]
I have the exact same specs and used your EFI and can get mac os big sur to boot and install but it still doesn't show wifi but has Bluetooth I have tried disabling airport itlwm and enabling  itlwn but nothing any help would be great

**Comment by xealstorm** [comment]
Hi @skydiives2 
I had no problems with Big Sur but I had a similar problem on Ventura.
This is how I solved it:
1. I replaced the BigSurface.kext with the [latest release](https://github.com/Xiashangning/BigSurface/releases/tag/v6.3)
2. I also replaced the BlueToolFixup.kext from the [latest release](https://github.com/acidanthera/BrcmPatchRAM/releases/tag/2.6.4)
3. And (probably most important): I downloaded Airportitlwm for Ventura from [here](https://www.tonymacx86.com/threads/lilu-and-friends-kext-downloads.321537/)

After that I have bluetooth and wi-fi working on Ventura. Hopefully you can make it work on Big Sur too! 

P.S. I guess, you may skip 1. and 2. and try the step 3. right away since you're not on the latest macOS.

**Comment by EricKY26** [comment]
Hi @xealstorm 
From what you wrote in your last comment, I guess that you run the latest macOS Ventura successfully on your Surface Pro 7, am I right?

I use macOS Monterey 12.6, and just 2 days ago, I tried to upgrade the system to 13.1 as it said in software update, but I ended up getting stuck after upgrading to macOS 13.1, the system got crashed each time after I login to it, and then restart itself.

do you have a chance to know what is happening and what should I do to prevent all this crash and restart loop?

**Comment by xealstorm** [comment]
Hey @EricKY26 
I think you should do the step 3 from my answer above. (steps 1 and 2 are optional)
Updating that kext should help. 

A side note. BigSurface has a bug on Ventura. If you detach the TypeCover or do the system Shutdown, it will restart the system. Quite annoying sometimes.

**Comment by EricKY26** [comment]
@xealstorm 
Thank you so much.
I'll update BigSurface.kext, BlueToolFixup.kext and Airportitlwm for Ventura.

And I just check my other kexts, most of them have a new version, so I think I'll just update them all in case some other bugs will crash Ventura.


> If you detach the TypeCover or do the system Shutdown, it will restart the system. Quite annoying sometimes.

Oh, That is annoying in some cases. Thanks for the tip.

**Comment by badstorm** [comment]
New release available.
